In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [4]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [5]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [6]:
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [7]:
dependent=dataset[[ 'charges']]
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.3,random_state=0)

In [9]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
param_grid={'n_estimators':[10,20,30,40,50,100],'criterion':['squared_error', 'absolute_error', 'friedman_mse', 'poisson'],'bootstrap':[True]}
grid=GridSearchCV(RandomForestRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(x_train,y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

C:\Users\gayut\anaconda3\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'bootstrap': [True],
                         'criterion': ['squared_error', 'absolute_error',
                                       'friedman_mse', 'poisson'],
                         'n_estimators': [10, 20, 30, 40, 50, 100]},
             verbose=3)

In [10]:
result=grid.cv_results_
result

{'mean_fit_time': array([0.06906552, 0.13068299, 0.17513905, 0.2189199 , 0.28867621,
        0.49517126, 0.19598632, 0.34160438, 0.48204851, 0.62433214,
        0.76609178, 1.59149451, 0.04213948, 0.08166881, 0.12187901,
        0.15515938, 0.19550138, 0.41754251, 0.04777761, 0.1091938 ,
        0.16874647, 0.21856394, 0.27585549, 0.47729588]),
 'std_fit_time': array([0.00335259, 0.0189146 , 0.01537137, 0.00906131, 0.01791536,
        0.02401035, 0.01659158, 0.00994348, 0.00968618, 0.00628855,
        0.01179806, 0.03214838, 0.00133098, 0.00143564, 0.00247488,
        0.00313946, 0.0029179 , 0.01570178, 0.00140805, 0.01047957,
        0.00634043, 0.00712013, 0.01408327, 0.01682003]),
 'mean_score_time': array([0.00892625, 0.00965633, 0.00887918, 0.01126375, 0.01069198,
        0.016785  , 0.00719528, 0.00567207, 0.00621476, 0.00831728,
        0.00862446, 0.01579823, 0.00425391, 0.00539546, 0.00617361,
        0.00749021, 0.00886207, 0.02026219, 0.00454273, 0.00686307,
        0.00768881, 0.01041217, 0.01058979, 0.01616445]),
 'std_score_time': array([0.00196697, 0.00302138, 0.00150001, 0.00150946, 0.00115004,
        0.00105969, 0.00146874, 0.00066998, 0.00048656, 0.00106343,
        0.00077991, 0.00267055, 0.00039835, 0.0004696 , 0.00046072,
        0.00026426, 0.00037852, 0.00597946, 0.00052986, 0.00204112,
        0.00087544, 0.00184673, 0.00075482, 0.00316985]),
 'param_bootstrap': masked_array(data=[True, True, True, True, True, True, True, True, True,
                    True, True, True, True, True, True, True, True, True,
                    True, True, True, True, True, True],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=True),
 'param_criterion': masked_array(data=['squared_error', 'squared_error', 'squared_error',
                    'squared_error', 'squared_error', 'squared_error',
                    'absolute_error', 'absolute_error', 'absolute_error',
                    'absolute_error', 'absolute_error', 'absolute_error',
                    'friedman_mse', 'friedman_mse', 'friedman_mse',
                    'friedman_mse', 'friedman_mse', 'friedman_mse',
                    'poisson', 'poisson', 'poisson', 'poisson', 'poisson',
                    'poisson'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_n_estimators': masked_array(data=[10, 20, 30, 40, 50, 100, 10, 20, 30, 40, 50, 100, 10,
                    20, 30, 40, 50, 100, 10, 20, 30, 40, 50, 100],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=999999),
 'params': [{'bootstrap': True,
   'criterion': 'squared_error',
   'n_estimators': 10},
  {'bootstrap': True, 'criterion': 'squared_error', 'n_estimators': 20},
  {'bootstrap': True, 'criterion': 'squared_error', 'n_estimators': 30},
  {'bootstrap': True, 'criterion': 'squared_error', 'n_estimators': 40},
  {'bootstrap': True, 'criterion': 'squared_error', 'n_estimators': 50},
  {'bootstrap': True, 'criterion': 'squared_error', 'n_estimators': 100},
  {'bootstrap': True, 'criterion': 'absolute_error', 'n_estimators': 10},
  {'bootstrap': True, 'criterion': 'absolute_error', 'n_estimators': 20},
  {'bootstrap': True, 'criterion': 'absolute_error', 'n_estimators': 30},
  {'bootstrap': True, 'criterion': 'absolute_error', 'n_estimators': 40},
  {'bootstrap': True, 'criterion': 'absolute_error', 'n_estimators': 50},
  {'bootstrap': True, 'criterion': 'absolute_error', 'n_estimators': 100},
  {'bootstrap': True, 'criterion': 'friedman_mse', 'n_estimators': 10},
  {'bootstrap': True, 'criterion': 'friedman_mse', 'n_estimators': 20},
  {'bootstrap': True, 'criterion': 'friedman_mse', 'n_estimators': 30},
  {'bootstrap': True, 'criterion': 'friedman_mse', 'n_estimators': 40},
  {'bootstrap': True, 'criterion': 'friedman_mse', 'n_estimators': 50},
  {'bootstrap': True, 'criterion': 'friedman_mse', 'n_estimators': 100},
  {'bootstrap': True, 'criterion': 'poisson', 'n_estimators': 10},
  {'bootstrap': True, 'criterion': 'poisson', 'n_estimators': 20},
  {'bootstrap': True, 'criterion': 'poisson', 'n_estimators': 30},
  {'bootstrap': True, 'criterion': 'poisson', 'n_estimators': 40},
  {'bootstrap': True, 'criterion': 'poisson', 'n_estimators': 50},
  {'bootstrap': True, 'criterion': 'poisson', 'n_estimators': 100}],
 'split0_test_score': array([0.84759102, 0.85487277, 0.86055694, 0.85939008, 0.86606771,
        0.86436662, 0.8121185 , 0.85687642, 0.85207552, 0.84462949,
        0.84744463, 0.84727578, 0.85271276, 0.8631935 , 0.85459021,
        0.86242926, 0.86218386, 0.86364914, 0.85578365, 0.86197365,
        0.86797099, 0.86300173, 0.85512242, 0.86694995]),
 'split1_test_score': array([0.7616116 , 0.75199174, 0.7595296 , 0.76524921, 0.7683154 ,
        0.76626175, 0.76872285, 0.76697227, 0.76484195, 0.78793715,
        0.77824588, 0.77507796, 0.74065332, 0.75522077, 0.77401529,
        0.7698271 , 0.76760519, 0.7685385 , 0.76305753, 0.75605517,
        0.75689331, 0.76304286, 0.76559597, 0.75917193]),
 'split2_test_score': array([0.78911259, 0.81038261, 0.81434746, 0.81586288, 0.81250971,
        0.81101805, 0.78310843, 0.78847355, 0.79244228, 0.79392136,
        0.79125278, 0.79431076, 0.79920196, 0.80192691, 0.81554732,
        0.81039067, 0.81145369, 0.81299212, 0.81241504, 0.80916757,
        0.80841384, 0.81329099, 0.80621092, 0.81667377]),
 'split3_test_score': array([0.78399081, 0.80483122, 0.79393416, 0.7956218 , 0.79877897,
        0.80095841, 0.79016519, 0.7920846 , 0.80230048, 0.79541729,
        0.79828753, 0.79763017, 0.78255877, 0.788432  , 0.80421463,
        0.77864959, 0.79152786, 0.79230626, 0.78151325, 0.79866857,
        0.79165584, 0.80372998, 0.79479704, 0.80635029]),
 'split4_test_score': array([0.77010118, 0.75780757, 0.77201675, 0.76649532, 0.76977176,
        0.7741672 , 0.74106243, 0.75762681, 0.76030466, 0.7703059 ,
        0.763711  , 0.76504108, 0.75312049, 0.75347484, 0.76552378,
        0.7701768 , 0.7686198 , 0.77309205, 0.77360969, 0.77145425,
        0.7631363 , 0.77140329, 0.77257961, 0.77097239]),
 'mean_test_score': array([0.79048144, 0.79597718, 0.80007698, 0.80052386, 0.80308871,
        0.8033544 , 0.77903548, 0.79240673, 0.79439298, 0.79844224,
        0.79578836, 0.79586715, 0.78564946, 0.7924496 , 0.80277825,
        0.79829469, 0.80027808, 0.80211561, 0.79727583, 0.79946384,
        0.79761406, 0.80289377, 0.79886119, 0.80402366]),
 'std_test_score': array([0.03018055, 0.03780539, 0.03558278, 0.03500512, 0.0357572 ,
        0.03468348, 0.02359343, 0.0347231 , 0.03295113, 0.02475828,
        0.02839677, 0.02839301, 0.03942967, 0.04003917, 0.03182701,
        0.03534546, 0.03493866, 0.03455629, 0.03356128, 0.03652703,
        0.03987262, 0.03550074, 0.03172746, 0.03802426]),
 'rank_test_score': array([22, 16,  9,  7,  3,  2, 24, 21, 19, 12, 18, 17, 23, 20,  5, 13,  8,
         6, 15, 10, 14,  4, 11,  1], dtype=int32)}

In [11]:
table=pd.DataFrame.from_dict(result)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_bootstrap,param_criterion,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.069066,0.003353,0.008926,0.001967,True,squared_error,10,"{'bootstrap': True, 'criterion': 'squared_erro...",0.847591,0.761612,0.789113,0.783991,0.770101,0.790481,0.030181,22
1,0.130683,0.018915,0.009656,0.003021,True,squared_error,20,"{'bootstrap': True, 'criterion': 'squared_erro...",0.854873,0.751992,0.810383,0.804831,0.757808,0.795977,0.037805,16
2,0.175139,0.015371,0.008879,0.001500,True,squared_error,30,"{'bootstrap': True, 'criterion': 'squared_erro...",0.860557,0.759530,0.814347,0.793934,0.772017,0.800077,0.035583,9
3,0.218920,0.009061,0.011264,0.001509,True,squared_error,40,"{'bootstrap': True, 'criterion': 'squared_erro...",0.859390,0.765249,0.815863,0.795622,0.766495,0.800524,0.035005,7
4,0.288676,0.017915,0.010692,0.001150,True,squared_error,50,"{'bootstrap': True, 'criterion': 'squared_erro...",0.866068,0.768315,0.812510,0.798779,0.769772,0.803089,0.035757,3
5,0.495171,0.024010,0.016785,0.001060,True,squared_error,100,"{'bootstrap': True, 'criterion': 'squared_erro...",0.864367,0.766262,0.811018,0.800958,0.774167,0.803354,0.034683,2
6,0.195986,0.016592,0.007195,0.001469,True,absolute_error,10,"{'bootstrap': True, 'criterion': 'absolute_err...",0.812119,0.768723,0.783108,0.790165,0.741062,0.779035,0.023593,24
7,0.341604,0.009943,0.005672,0.000670,True,absolute_error,20,"{'bootstrap': True, 'criterion': 'absolute_err...",0.856876,0.766972,0.788474,0.792085,0.757627,0.792407,0.034723,21
8,0.482049,0.009686,0.006215,0.000487,True,absolute_error,30,"{'bootstrap': True, 'criterion': 'absolute_err...",0.852076,0.764842,0.792442,0.802300,0.760305,0.794393,0.032951,19
9,0.624332,0.006289,0.008317,0.001063,True,absolute_error,40,"{'bootstrap': True, 'criterion': 'absolute_err...",0.844629,0.787937,0.793921,0.795417,0.770306,0.798442,0.024758,12
10,0.766092,0.011798,0.008624,0.000780,True,absolute_error,50,"{'bootstrap': True, 'criterion': 'absolute_err...",0.847445,0.778246,0.791253,0.798288,0.763711,0.795788,0.028397,18
11,1.591495,0.032148,0.015798,0.002671,True,absolute_error,100,"{'bootstrap': True, 'criterion': 'absolute_err...",0.847276,0.775078,0.794311,0.797630,0.765041,0.795867,0.028393,17
12,0.042139,0.001331,0.004254,0.000398,True,friedman_mse,10,"{'bootstrap': True, 'criterion': 'friedman_mse...",0.852713,0.740653,0.799202,0.782559,0.753120,0.785649,0.039430,23
13,0.081669,0.001436,0.005395,0.000470,True,friedman_mse,20,"{'bootstrap': True, 'criterion': 'friedman_mse...",0.863193,0.755221,0.801927,0.788432,0.753475,0.792450,0.040039,20
14,0.121879,0.002475,0.006174,0.000461,True,friedman_mse,30,"{'bootstrap': True, 'criterion': 'friedman_mse...",0.854590,0.774015,0.815547,0.804215,0.765524,0.802778,0.031827,5
15,0.155159,0.003139,0.007490,0.000264,True,friedman_mse,40,"{'bootstrap': True, 'criterion': 'friedman_mse...",0.862429,0.769827,0.810391,0.778650,0.770177,0.798295,0.035345,13
16,0.195501,0.002918,0.008862,0.000379,True,friedman_mse,50,"{'bootstrap': True, 'criterion': 'friedman_mse...",0.862184,0.767605,0.811454,0.791528,0.768620,0.800278,0.034939,8
17,0.417543,0.015702,0.020262,0.005979,True,friedman_mse,100,"{'bootstrap': True, 'criterion': 'friedman_mse...",0.863649,0.768538,0.812992,0.792306,0.773092,0.802116,0.034556,6
18,0.047778,0.001408,0.004543,0.000530,True,poisson,10,"{'bootstrap': True, 'criterion': 'poisson', 'n...",0.855784,0.763058,0.812415,0.781513,0.773610,0.797276,0.033561,15
19,0.109194,0.010480,0.006863,0.002041,True,poisson,20,"{'bootstrap': True, 'criterion': 'poisson', 'n...",0.861974,0.756055,0.809168,0.798669,0.771454,0.799464,0.036527,10
20,0.168746,0.006340,0.007689,0.000875,True,poisson,30,"{'bootstrap': True, 'criterion': 'poisson', 'n...",0.867971,0.756893,0.808414,0.791656,0.763136,0.797614,0.039873,14
21,0.218564,0.007120,0.010412,0.001847,True,poisson,40,"{'bootstrap': True, 'criterion': 'poisson', 'n...",0.863002,0.763043,0.813291,0.803730,0.771403,0.802894,0.035501,4
22,0.275855,0.014083,0.010590,0.000755,True,poisson,50,"{'bootstrap': True, 'criterion': 'poisson', 'n...",0.855122,0.765596,0.806211,0.794797,0.772580,0.798861,0.031727,11
23,0.477296,0.016820,0.016164,0.003170,True,poisson,100,"{'bootstrap': True, 'criterion': 'poisson', 'n...",0.866950,0.759172,0.816674,0.806350,0.770972,0.804024,0.038024,1

In [12]:
table.columns

Index(['mean_fit_time', 'std_fit_time', 'mean_score_time', 'std_score_time',
       'param_bootstrap', 'param_criterion', 'param_n_estimators', 'params',
       'split0_test_score', 'split1_test_score', 'split2_test_score',
       'split3_test_score', 'split4_test_score', 'mean_test_score',
       'std_test_score', 'rank_test_score'],
      dtype='object')

In [13]:
table=table.sort_values(by='rank_test_score')
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_bootstrap,param_criterion,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
23,0.477296,0.016820,0.016164,0.003170,True,poisson,100,"{'bootstrap': True, 'criterion': 'poisson', 'n...",0.866950,0.759172,0.816674,0.806350,0.770972,0.804024,0.038024,1
5,0.495171,0.024010,0.016785,0.001060,True,squared_error,100,"{'bootstrap': True, 'criterion': 'squared_erro...",0.864367,0.766262,0.811018,0.800958,0.774167,0.803354,0.034683,2
4,0.288676,0.017915,0.010692,0.001150,True,squared_error,50,"{'bootstrap': True, 'criterion': 'squared_erro...",0.866068,0.768315,0.812510,0.798779,0.769772,0.803089,0.035757,3
21,0.218564,0.007120,0.010412,0.001847,True,poisson,40,"{'bootstrap': True, 'criterion': 'poisson', 'n...",0.863002,0.763043,0.813291,0.803730,0.771403,0.802894,0.035501,4
14,0.121879,0.002475,0.006174,0.000461,True,friedman_mse,30,"{'bootstrap': True, 'criterion': 'friedman_mse...",0.854590,0.774015,0.815547,0.804215,0.765524,0.802778,0.031827,5
17,0.417543,0.015702,0.020262,0.005979,True,friedman_mse,100,"{'bootstrap': True, 'criterion': 'friedman_mse...",0.863649,0.768538,0.812992,0.792306,0.773092,0.802116,0.034556,6
3,0.218920,0.009061,0.011264,0.001509,True,squared_error,40,"{'bootstrap': True, 'criterion': 'squared_erro...",0.859390,0.765249,0.815863,0.795622,0.766495,0.800524,0.035005,7
16,0.195501,0.002918,0.008862,0.000379,True,friedman_mse,50,"{'bootstrap': True, 'criterion': 'friedman_mse...",0.862184,0.767605,0.811454,0.791528,0.768620,0.800278,0.034939,8
2,0.175139,0.015371,0.008879,0.001500,True,squared_error,30,"{'bootstrap': True, 'criterion': 'squared_erro...",0.860557,0.759530,0.814347,0.793934,0.772017,0.800077,0.035583,9
19,0.109194,0.010480,0.006863,0.002041,True,poisson,20,"{'bootstrap': True, 'criterion': 'poisson', 'n...",0.861974,0.756055,0.809168,0.798669,0.771454,0.799464,0.036527,10
22,0.275855,0.014083,0.010590,0.000755,True,poisson,50,"{'bootstrap': True, 'criterion': 'poisson', 'n...",0.855122,0.765596,0.806211,0.794797,0.772580,0.798861,0.031727,11
9,0.624332,0.006289,0.008317,0.001063,True,absolute_error,40,"{'bootstrap': True, 'criterion': 'absolute_err...",0.844629,0.787937,0.793921,0.795417,0.770306,0.798442,0.024758,12
15,0.155159,0.003139,0.007490,0.000264,True,friedman_mse,40,"{'bootstrap': True, 'criterion': 'friedman_mse...",0.862429,0.769827,0.810391,0.778650,0.770177,0.798295,0.035345,13
20,0.168746,0.006340,0.007689,0.000875,True,poisson,30,"{'bootstrap': True, 'criterion': 'poisson', 'n...",0.867971,0.756893,0.808414,0.791656,0.763136,0.797614,0.039873,14
18,0.047778,0.001408,0.004543,0.000530,True,poisson,10,"{'bootstrap': True, 'criterion': 'poisson', 'n...",0.855784,0.763058,0.812415,0.781513,0.773610,0.797276,0.033561,15
1,0.130683,0.018915,0.009656,0.003021,True,squared_error,20,"{'bootstrap': True, 'criterion': 'squared_erro...",0.854873,0.751992,0.810383,0.804831,0.757808,0.795977,0.037805,16
11,1.591495,0.032148,0.015798,0.002671,True,absolute_error,100,"{'bootstrap': True, 'criterion': 'absolute_err...",0.847276,0.775078,0.794311,0.797630,0.765041,0.795867,0.028393,17
10,0.766092,0.011798,0.008624,0.000780,True,absolute_error,50,"{'bootstrap': True, 'criterion': 'absolute_err...",0.847445,0.778246,0.791253,0.798288,0.763711,0.795788,0.028397,18
8,0.482049,0.009686,0.006215,0.000487,True,absolute_error,30,"{'bootstrap': True, 'criterion': 'absolute_err...",0.852076,0.764842,0.792442,0.802300,0.760305,0.794393,0.032951,19
13,0.081669,0.001436,0.005395,0.000470,True,friedman_mse,20,"{'bootstrap': True, 'criterion': 'friedman_mse...",0.863193,0.755221,0.801927,0.788432,0.753475,0.792450,0.040039,20
7,0.341604,0.009943,0.005672,0.000670,True,absolute_error,20,"{'bootstrap': True, 'criterion': 'absolute_err...",0.856876,0.766972,0.788474,0.792085,0.757627,0.792407,0.034723,21
0,0.069066,0.003353,0.008926,0.001967,True,squared_error,10,"{'bootstrap': True, 'criterion': 'squared_erro...",0.847591,0.761612,0.789113,0.783991,0.770101,0.790481,0.030181,22
12,0.042139,0.001331,0.004254,0.000398,True,friedman_mse,10,"{'bootstrap': True, 'criterion': 'friedman_mse...",0.852713,0.740653,0.799202,0.782559,0.753120,0.785649,0.039430,23
6,0.195986,0.016592,0.007195,0.001469,True,absolute_error,10,"{'bootstrap': True, 'criterion': 'absolute_err...",0.812119,0.768723,0.783108,0.790165,0.741062,0.779035,0.023593,24

In [14]:
table.columns

Index(['mean_fit_time', 'std_fit_time', 'mean_score_time', 'std_score_time',
       'param_bootstrap', 'param_criterion', 'param_n_estimators', 'params',
       'split0_test_score', 'split1_test_score', 'split2_test_score',
       'split3_test_score', 'split4_test_score', 'mean_test_score',
       'std_test_score', 'rank_test_score'],
      dtype='object')

In [15]:
rdtable=table[['param_criterion', 'param_n_estimators', 'param_bootstrap','std_test_score', 'rank_test_score','mean_test_score']]
rdtable.columns=[['Criterion','N_Estimators','Bootstrap','SDScore','Mean_Test_Score','Rank']]
rdtable

         Criterion N_Estimators Bootstrap   SDScore Mean_Test_Score      Rank
23         poisson          100      True  0.038024               1  0.804024
5    squared_error          100      True  0.034683               2  0.803354
4    squared_error           50      True  0.035757               3  0.803089
21         poisson           40      True  0.035501               4  0.802894
14    friedman_mse           30      True  0.031827               5  0.802778
17    friedman_mse          100      True  0.034556               6  0.802116
3    squared_error           40      True  0.035005               7  0.800524
16    friedman_mse           50      True  0.034939               8  0.800278
2    squared_error           30      True  0.035583               9  0.800077
19         poisson           20      True  0.036527              10  0.799464
22         poisson           50      True  0.031727              11  0.798861
9   absolute_error           40      True  0.024758              12  0.798442
15    friedman_mse           40      True  0.035345              13  0.798295
20         poisson           30      True  0.039873              14  0.797614
18         poisson           10      True  0.033561              15  0.797276
1    squared_error           20      True  0.037805              16  0.795977
11  absolute_error          100      True  0.028393              17  0.795867
10  absolute_error           50      True  0.028397              18  0.795788
8   absolute_error           30      True  0.032951              19  0.794393
13    friedman_mse           20      True  0.040039              20  0.792450
7   absolute_error           20      True  0.034723              21  0.792407
0    squared_error           10      True  0.030181              22  0.790481
12    friedman_mse           10      True  0.039430              23  0.785649
6   absolute_error           10      True  0.023593              24  0.779035

In [16]:
y_pred=grid.predict(x_test)

In [17]:
from sklearn.metrics import r2_score
r2score=r2_score(y_test,y_pred)
r2score

0.8516692650639337

In [18]:
Age = float(input("Please enter your age: "))
BMI = float(input("Please enter your BMI: "))
Children = float(input("Please enter number of children: "))

Gender = input("Please enter your gender: ").lower()
if Gender == "male":
    gender = 1
else:
    gender = 0

Smoker = input("Do you smoke? (yes/no): ").lower()
if Smoker == "yes":
    smoker = 1
else:
    smoker = 0

charger_prediction = grid.predict([[Age, BMI, Children, gender, smoker]])

print("Estimated Charge is:", charger_prediction[0])

Please enter your age:  23
Please enter your BMI:  34
Please enter number of children:  3
Please enter your gender:  male
Do you smoke? (yes/no):  yes

Estimated Charge is: 35899.02770550002

C:\Users\gayut\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(